{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRole
metadata:
  name: {{ include "namespacerole-operator.fullname" . }}
  labels:
    {{- include "namespacerole-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
{{ end }}
